language: r
cache: packages
sudo: false
warnings_are_errors: false

addons:
   apt:
     packages:
       - libgsl0-dev
       - libxml2-dev
       - build-essential
       - libssl-dev
       - libsasl2-dev
       - libpcap0.8-dev
       - libcurl4-openssl-dev
       - libgomp1
       - libxt6
       - libsm6
       - less
       - pkg-config
       - libhiredis-dev
       - libapparmor-dev
       
services: 
   - redis-server
#script: 
#   - Rscript -e "library(testthat); #source('run_tests.R')"

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  slack: ntyndall:ffjQMwuOwDH6BvaNDpDzRO2x
  email:
    on_success: change
    on_failure: change
