language: r
cache: packages
sudo: false
addons:
   apt:
     packages:
       - libgsl0-dev
       - libxml2-dev
       - libhiredis-dev
services: 
   - redis-server
script: 
   - Rscript -e "library(testthat); source('runTests.R')"

notifications:
  slack: ntyndall:ffjQMwuOwDH6BvaNDpDzRO2x
