language: r
cache: packages
sudo: false
warnings_are_errors: false

addons:
   apt:
     packages:
       - libgsl0-dev
       - libxml2-dev
        - pkg-config
       - libhiredis-dev0.13
       - libapparmor-dev
services: 
   - redis-server
#script: 
#   - Rscript -e "library(testthat); #source('run_tests.R')"

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  slack: ntyndall:ffjQMwuOwDH6BvaNDpDzRO2x
  email:
    on_success: change
    on_failure: change
