language: r
cache: packages
sudo: false
addons:
   apt:
     packages:
       - libgsl0-dev
       - libxml2-dev
       - libhiredis-dev

script: 
   - Rscript -e runTests.R
   - val = $(Rscript -e "library(testthat);
             result <- source('runTests.R');
             result <- as.integer(result$value);
             if (result > 0) { 1 } else { 0 }");
             valInt=${val/.*};
             if [ "$valInt" -gt 0 ]; then exit 1; fi

notifications:
  slack: ntyndall:ffjQMwuOwDH6BvaNDpDzRO2x
